// <auto-generated />
using System;
using API_DFSK.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_DFSK.Migrations
{
    [DbContext(typeof(ConcesionarioDfskContext))]
    [Migration("20240807203517_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Repuesto", b =>
                {
                    b.Property<int>("IdRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRepuesto"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdRepuesto")
                        .HasName("PK__Repuesto__75B30774EDDF74CD");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Solicitude", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<double?>("Cantidad")
                        .HasColumnType("float");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaLlegada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdRepuesto")
                        .HasColumnType("int");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdSolicitud")
                        .HasName("PK__Solicitu__85E95DA75C3B08DD");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdRepuesto");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int?>("Anho")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("VIN");

                    b.HasKey("IdVehiculo")
                        .HasName("PK__Vehiculo__AA088620633F3CD2");

                    b.HasIndex(new[] { "Vin" }, "UQ__Vehiculo__C5DF234C699ED050")
                        .IsUnique()
                        .HasFilter("[VIN] IS NOT NULL");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Vendedore", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVendedor"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdVendedor")
                        .HasName("PK__Vendedor__2033EECC06D7C763");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Repuesto", b =>
                {
                    b.HasOne("API_DFSK.Models.ConcesionarioDFSK.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Repuestos")
                        .HasForeignKey("IdVehiculo")
                        .IsRequired()
                        .HasConstraintName("FK_Repuestos_Vehiculos");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Solicitude", b =>
                {
                    b.HasOne("API_DFSK.Models.ConcesionarioDFSK.Estado", "IdEstadoNavigation")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Solicitudes_Estados");

                    b.HasOne("API_DFSK.Models.ConcesionarioDFSK.Repuesto", "IdRepuestoNavigation")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdRepuesto")
                        .IsRequired()
                        .HasConstraintName("FK__Solicitud__Repue__2D27B809");

                    b.HasOne("API_DFSK.Models.ConcesionarioDFSK.Vendedore", "IdVendedorNavigation")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdVendedor")
                        .IsRequired()
                        .HasConstraintName("FK__Solicitud__Vende__2C3393D0");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdRepuestoNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Estado", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Repuesto", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Vehiculo", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("API_DFSK.Models.ConcesionarioDFSK.Vendedore", b =>
                {
                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
